CREATE TABLE IF NOT EXISTS game (
  "id" INTEGER PRIMARY KEY,
  "name" TEXT,
  genres INTEGER[],
  slug TEXT,
  summary TEXT,
  age_ratings INTEGER[],
  artworks INTEGER[],
  category INTEGER,
  cover INTEGER,
  created_at INTEGER,
  external_games INTEGER[],
  first_release_date INTEGER,
  game_engines INTEGER[],
  game_modes INTEGER[],
  involved_companies INTEGER[],
  multiplayer_modes INTEGER[],
  platforms INTEGER[],
  release_dates INTEGER[],
  screenshots INTEGER[],
  similar_games INTEGER[],
  tags INTEGER[],
  themes INTEGER[],
  updated_at INTEGER,
  url TEXT,
  websites INTEGER[],
  checksum TEXT,
  language_supports INTEGER[]
)
